[app_settings]
app_port = 8000
app_version = "1.0.0"
app_name = "pay-service"
app_host = "127.0.0.1"
app_mount = "/api/v1"

[db_settings]
db_name = "pay_service"
db_user = "my_user"
db_password = "my_password"
db_host = "localhost"
db_port = 5432
